FROM scratch
# ADD vineseed-7-x86_64-docker.tar.xz /
# ADD VineSeed_x86_64-docker-20201216.tar.xz /
ADD VineSeed_x86_64-20221127.tar.gz /

LABEL maintainer="Munehiro Yamamoto <munepi@vinelinux.org>" \
        org.label-schema.schema-version="1.0" \
        org.label-schema.name="VineSeed Base Image" \
        org.label-schema.build-date="20221127"

# ENTRYPOINT [ "/bin/bash", "-c" ]
# CMD ["cat /etc/vine-release"]
##
CMD [ "/bin/bash" ]
