FROM scratch
# ADD vineseed-7-x86_64-docker.tar.xz /
ADD VineSeed_x86_64-docker-20190607.tar.xz /

LABEL maintainer="Munehiro Yamamoto <munepi@vinelinux.org>" \
        org.label-schema.schema-version="1.0" \
        org.label-schema.name="VineSeed Base Image" \
        org.label-schema.build-date="20190607"

# ENTRYPOINT [ "/bin/bash", "-c" ]
# CMD ["cat /etc/vine-release"]
## 
CMD [ "/bin/bash" ]
